# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- name: install necessary dependencies on Ubuntu
  apt: 
    name:
      - moreutils     # for sponge command
      - jq
    update-cache: yes
  become: yes

- name: create config directory
  file:
    path: "{{ _configs_dest }}"
    state: directory

- name: copy configs
  copy:
    src: "{{ _git_repo_dest }}/configs/{{ item }}"
    dest: "{{ _configs_dest }}/"
    directory_mode: yes
    remote_src: yes
  with_items:
    - appliance.json
    - eaa.json
    - certsigner.json
    - eaa_certrequest.json
    - edgedns_certrequest.json
    - interfaceservice_certrequest.json

- name: copy interfaceservice config
  copy:
    src: "{{ _git_repo_dest }}/configs/interfaceservice.json"
    dest: "{{ _configs_dest }}/"
    directory_mode: yes
    remote_src: yes
  when: "'kubeovn' in kubernetes_cnis"

- name: customize eaa.json
  block:
    - name: change validation endpoint for EAA
      shell: jq '.ValidationEndpoint=""' '{{ _configs_dest }}/eaa.json' | sponge '{{ _configs_dest }}/eaa.json'
    - name: change EAA common name
      shell: jq '.Certs.CommonName="eaa.openness"' '{{ _configs_dest }}/eaa.json' | sponge '{{ _configs_dest }}/eaa.json'
    - name: change Kafka URL
      shell: jq '.KafkaBroker="{{ kafka_cluster }}-kafka-bootstrap.kafka:9093"' '{{ _configs_dest }}/eaa.json' | sponge '{{ _configs_dest }}/eaa.json'

- name: customize Certificate Requester configs
  block:
    - name: include node name in EdgeDNS CSR name
      shell: jq '.CSR.Name="edgedns-{{ node_name }}"' '{{ _configs_dest }}/edgedns_certrequest.json' | sponge '{{ _configs_dest }}/edgedns_certrequest.json'
    - name: include node name in Interfaceservice CSR name
      shell: >
        jq '.CSR.Name="interfaceservice-{{ node_name }}"' '{{ _configs_dest }}/interfaceservice_certrequest.json' |
        sponge '{{ _configs_dest }}/interfaceservice_certrequest.json'

- name: copy logrotate config
  copy:
    src: logrotate_edgenode
    dest: /etc/logrotate.d/edgenode
    remote_src: no
  become: yes
